apiVersion: v1
kind: Service

metadata:
  name: tasks-service

spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000 # Outside facing port
      targetPort: 8000 # Inside of the pod that port will be forwarded
