apiVersion: v1
kind: Service

metadata:
  name: users-service

spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080 # Outside facing port
      targetPort: 8080 # Inside of the pod that port will be forwarded
