apiVersion: v1
kind: PersistentVolume

metadata:
  name: story-app-host-pv
spec:
  capacity:
    storage: 1Gi

  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # Multiple pods but same node
    # - ReadOnlyMany # Multiple pods and different nodes which `hostPath` cannot use
    # - ReadWriteMany # Additional write access

  hostPath:
    path: /data
    type: DirectoryOrCreate
