apiVersion: v1
kind: Service

metadata:
  name: story-app-ser

spec:
  selector:
    app: story-app-pod
  type: LoadBalancer
  # Required, otherwise "story-app-ser has no node port" error
  # Because by default it is just expose internally inside the cluster
  # And not reachable from the outside

  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 3000
