apiVersion: v1
kind: Service

metadata:
  name: k8s-second-ser

spec:
  selector:
    app: k8s-second-pod

  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080

  type: LoadBalancer

--- # Defines a new object

apiVersion: apps/v1
kind: Deployment

metadata:
  name: k8s-second-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-second-pod
      tier: backend

  template:
    metadata:
      labels:
        app: k8s-second-pod
        tier: backend

    spec:
      containers:
        - name: k8s-second-con
          image: darrela/k8s-first
